apiVersion: v1
kind: Service
metadata:
  name: inspiring-quotes-api
spec:
  type: NodePort
  selector:
    app: inspiring-quotes-api
  ports:
    - protocol: TCP
      port: 80           # External port (can be left as 80)
      targetPort: 5000   # Flask app internal port
      nodePort: 30007    # NodePort exposed by Kubernetes
